### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by vhf**

### CODE REVIEW

**Review by ktk — APPROVED** [review]
Tnx makes all sense and does not break anything

**Comment by l00mi** [comment]
It will break some tests which do refer an exact string currently. Please do release as a new major version. I propose to wait until new stuff from @ktk is also ready.

**Comment by fnogatz** [comment]
So, finally, time to publish these changes as v1.1.1? :)

**Comment by ktk** [comment]
I can't remember what I wanted to add so I propose a new version indeed, @bergos can you do that.

**Pull request merged**
